# Copyright (C) 2015-2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
#
# OSSEC Application detection - (C) 2007 Daniel B. Cid - dcid@ossec.net
#
# Released under the same license as OSSEC.
# More details at the LICENSE file included with OSSEC or online
# at: https://www.gnu.org/licenses/gpl.html
#
# [Application name] [any or all] [reference]
# type:<entry name>;
#
# Type can be:
#             - f (for file or directory)
#             - r (registry entry)
#             - p (process running)
#
# Additional values:
# For the registry and for directories, use "->" to look for a specific entry and another
# "->" to look for the value.
# Also, use " -> r:^\. -> ..." to search all files in a directory
# For files, use "->" to look for a specific value in the file.
#
# Values can be preceded by: =: (for equal) - default
#                             r: (for ossec regexes)
#                             >: (for strcmp greater)
#                             <: (for strcmp  lower)
# Multiple patterns can be specified by using " && " between them.
# (All of them must match for it to return true).

checks:
 - id: 17000
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'f:\Program Files\Skype\Phone;'
     - 'f:\Documents and Settings\All Users\Documents\My Skype Pictures;'
     - 'f:\Documents and Settings\Skype;'
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\Skype;'
     - 'r:HKLM\SOFTWARE\Skype;'
     - 'r:HKEY_LOCAL_MACHINE\Software\Policies\Skype;'
     - 'p:r:Skype.exe;'
 - id: 17001
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\Yahoo! Messenger;'
     - 'r:HKLM\SOFTWARE\Yahoo;'
 - id: 17002
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'r:HKEY_CURRENT_USER\Software\Mirabilis\ICQ;'
 - id: 17003
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - http://www.aol.com
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\America Online\AOL Instant Messenger;'
     - 'r:HKEY_CLASSES_ROOT\aim\shell\open\command;'
     - 'r:HKEY_CLASSES_ROOT\AIM.Protocol;'
     - 'r:HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/x-aim;'
     - 'f:\Program Files\AIM95;'
     - 'p:r:aim.exe;'
 - id: 17004
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - http://www.msn.com
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSNMessenger;'
     - 'r:HKEY_CURRENT_USER\SOFTWARE\Microsoft\MSNMessenger;'
     - 'f:\Program Files\MSN Messenger;'
     - 'f:\Program Files\Messenger;'
     - 'p:r:msnmsgr.exe;'
 - id: 17005
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - http://www.icq.com
   condition: any
   rules:
     - 'r:HKLM\SOFTWARE\Mirabilis\ICQ;'
 - id: 17006
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'p:r:utorrent.exe;'
 - id: 17007
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Limewire;'
     - 'r:HKLM\software\microsoft\windows\currentversion\run -> limeshop;'
     - 'f:\Program Files\limewire;'
     - 'f:\Program Files\limeshop;'
 - id: 17008
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'f:\Program Files\kazaa;'
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\kazaa;'
     - 'f:\Documents and Settings\All Users\DESKTOP\Kazaa Media Desktop.lnk;'
     - 'f:\Documents and Settings\All Users\DESKTOP\Kazaa Promotions.lnk;'
     - 'f:%WINDIR%\System32\Cd_clint.dll;'
     - 'f:%WINDIR%\Sysnative\Cd_clint.dll;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\KAZAA;'
     - 'r:HKEY_CURRENT_USER\SOFTWARE\KAZAA;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\KAZAA;'
# http://vil.nai.com/vil/content/v_135023.htm
 - id: 17009
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - http://vil.nai.com/vil/content/v_135023.htm
   condition: any
   rules:
     - 'r:HKEY_CURRENT_USER\Software\Infotechnics;'
     - 'r:HKEY_CURRENT_USER\Software\Infotechnics\RX Toolbar;'
     - 'r:HKEY_CURRENT_USER\Software\RX Toolbar;'
     - 'r:HKEY_CLASSES_ROOT\BarInfoUrl.TBInfo;'
     - 'r:HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RX Toolbar;'
     - 'f:\Program Files\RXToolBar;'
# http://btfaq.com/serve/cache/18.html
 - id: 17010
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - http://btfaq.com/serve/cache/18.html
   condition: any
   rules:
     - 'f:\Program Files\BitTorrent;'
     - 'r:HKEY_CLASSES_ROOT\.torrent;'
     - 'r:HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/x-bittorrent;'
     - 'r:HKEY_CLASSES_ROOT\bittorrent;'
     - 'r:HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\BitTorrent;'
# http://www.gotomypc.com
 - id: 17011
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'f:\Program Files\Citrix\GoToMyPC;'
     - 'f:\Program Files\Citrix\GoToMyPC\g2svc.exe;'
     - 'f:\Program Files\Citrix\GoToMyPC\g2comm.exe;'
     - 'f:\Program Files\expertcity\GoToMyPC;'
     - 'r:HKLM\software\microsoft\windows\currentversion\run -> gotomypc;'
     - 'r:HKEY_LOCAL_MACHINE\software\citrix\gotomypc;'
     - 'r:HKEY_LOCAL_MACHINE\system\currentcontrolset\services\gotomypc;'
     - 'p:r:g2svc.exe;'
     - 'p:r:g2pre.exe;'
 - id: 17012
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TwaintecDll.TwaintecDllObj.1;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\twaintech;'
     - 'f:%WINDIR%\twaintec.dll;'
# http://www.symantec.com/security_response/writeup.jsp?docid=2004-062611-4548-99&tabid=2
 - id: 17013
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'f:\Program Files\ExploreAnywhere\SpyBuddy\sb32mon.exe;'
     - 'f:\Program Files\ExploreAnywhere\SpyBuddy;'
     - 'f:\Program Files\ExploreAnywhere;'
     - 'f:%WINDIR%\System32\sysicept.dll;'
     - 'f:%WINDIR%\Sysnative\sysicept.dll;'
     - 'r:HKEY_LOCAL_MACHINE\Software\ExploreAnywhere Software\SpyBuddy;'
 - id: 17014
   title: ""
   description: ""
   rationale: ""
   remediation: ""
   compliance:
    - cis: ""
    - cis_csc: ""
   references:
    - 
   condition: any
   rules:
     - 'r:HKLM\SOFTWARE\Avenue Media;'
     - 'r:HKEY_CLASSES_ROOT\\safesurfinghelper.iebho.1;'
     - 'r:HKEY_CLASSES_ROOT\\safesurfinghelper.iebho;'
